name: Coverity FullClient Baseline Analysis
on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: self-hosted
    
    env:
      COVERITY_CONNECT_URL: ${{ secrets.COVERITY_CONNECT_LOCAL_URL }}
      COVERITY_CONNECT_AUTHENTICATION_KEY: ${{ secrets.COVERITY_CONNECT_LOCAL_AUTHENTICATION_KEY }}
      COVERITY_CONNECT_AUTHENTICATION_FILE: coverity-connect.token

    steps:
      - uses: actions/checkout@v3

      - name: Coverity Scan (Full analysis)
        if: ${{ github.event_name != 'pull_request' }}
        shell: bash
        run: |
          ## Store access token in auth-key-file.
          echo ${{ secrets.COVERITY_CONNECT_LOCAL_AUTHENTICATION_KEY }} | base64 -d > ${COVERITY_CONNECT_AUTHENTICATION_FILE}
          chmod go-rwx ${COVERITY_CONNECT_AUTHENTICATION_FILE}
          ## Create lower case stream name.
          COVERITY_CONNECT_STREAM_NAME=${GITHUB_REPOSITORY##*/}-${GITHUB_REF##*/}
          COVERITY_CONNECT_STREAM_NAME=${COVERITY_CONNECT_STREAM_NAME,,}

          coverity scan \
            -o commit.connect.url=${{ secrets.COVERITY_CONNECT_LOCAL_URL }} \
            -o commit.connect.stream=${COVERITY_CONNECT_STREAM_NAME} \
            -o commit.connect.version=${GITHUB_SHA} \
            -o commit.connect.description="GitHub Workflow \'${GITHUB_WORKFLOW}\' for ${GITHUB_REPOSITORY}"

          coverity list > coverity.capture-file-listing.txt
          cat coverity.capture-file-listing.txt 
          cov-format-errors --dir idir --json-output-v7 coverity-results.json

      - name: Archive Coverity File Listing
        uses: actions/upload-artifact@v3
        with:
          name: coverity-capture-file-listing
          path: coverity.capture-file-listing.txt

      - name: Archive Coverity Scan Info
        uses: actions/upload-artifact@v3
        with:
          name: coverity-summary
          path: |
            idir/output/summary.txt
            coverity-results.json
