name: Polaris
on:
  push:
    branches: [ master-localscan ]

  #pull_request:
  #  branches: [ master, main ]

jobs:
  build:
    runs-on: self-hosted
    
    env:
      #SECURITY_GATE_FILTERS: '{ "severity": ["Higher", "Medium"], "cwe": [ "31955" ], "status": [ "new" ] }'
      SECURITY_GATE_FILTERS: '{ "severity": ["Higher"] }'

    steps:
      - uses: actions/checkout@v3

      - name: Synopsys Polaris (Full Analysis)
        if: ${{ github.event_name != 'pull_request' }}
        uses: jcroall/polaris-report-action@v0.1.0
        with:
          polaris-url: ${{ secrets.POLARIS_URL }}
          polaris-access-token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          debug: true
          generate-sarif: true
          polaris-command: --co analyze.mode=local analyze -w
          # Include the security gate filters - what should cause a policy failure
          security-gate-filters: ${{ env.SECURITY_GATE_FILTERS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Synopsys Processing local SARIF output
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo 'Processing findings ...'
          /opt/cov-analysis/bin/cov-format-errors --dir .synopsys/polaris/data/coverity/2022.6.0/idir --json-output-v10 .synopsys/polaris/local-scan-results.v10.json
          /opt/cov-analysis/node/bin/node /opt/cov-analysis/SARIF/cov-format-sarif-for-github.js --inputFile .synopsys/polaris/local-scan-results.v10.json --outputFile .synopsys/polaris/local-scan-results.sarif --githubUrl https://github.com --repoName mathkraemer/SecurityWebShop --checkoutPath mathkraemer/SecurityWebShop /opt/actions-runner/_work/SecurityWebShop/SecurityWebShop $(git rev-parse HEAD)
          
      - name: Upload SARIF Results
        if: ${{ github.event_name != 'pull_request' }}
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: .synopsys/polaris/local-scan-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: Coverity

      - name: Synopsys Polaris (Incremental Analysis)
        if: ${{ github.event_name == 'pull_request' }}
        uses: jcroall/polaris-report-action@v0.1.0
        with:
          polaris-url: ${{ secrets.POLARIS_URL }}
          polaris-access-token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          debug: true
          generate-sarif: true
          # $CHANGE_SET_FILE_PATH will be automatically replaced with a path to a file
          # listing the files changed in the GitHub Pull Request.
          #
          # If incremental is detected in the polaris command line, the results will be
          # read from the local NEW issues output rather than via web services.
          polaris-command: analyze -w --incremental $CHANGE_SET_FILE_PATH
          # Include the security gate filters - what should cause a policy failure
          security-gate-filters: ${{ env.SECURITY_GATE_FILTERS }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
