# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Synopsys Security Testing

on:
  workflow_dispatch:
    
  push:
    # At this time, it is recommended to run Polaris only on pushes to main branches
    # Pull request analysis will be supported by Polaris in the future
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: [self-hosted, Windows, X64]
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Synopsys Action
        uses: synopsys-sig/synopsys-action@v1.6.0
        with:
          #------------------------------------------COVERITY-----------------------------------------
          coverity_url: ${{ secrets.COVERITY_URL }}
          coverity_user: ${{ secrets.COVERITY_USER }}
          coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
          coverity_local: true
          coverity_install_directory: c:\Products\ca202312
          coverity_project_name: Security WebShop

          coverity_policy_view: 'Saftey Gate'
          coverity_prComment_enabled: true

          #------------------------------------------BLACKDUCK----------------------------------------
          blackduck_token: ${{ secrets.BLACKDUCK_TOKEN }}
          blackduck_url: ${{ secrets.BLACKDUCK_URL }}

          blackduck_scan_failure_severities: 'BLOCKER,CRITICAL'
          blackduck_fixpr_enabled: true
          blackduck_prcomment_enabled: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

          #------------------------------------------POLARIS------------------------------------------
          #polaris_server_url: ${{ secrets.POLARIS_SERVER_URL }}
          #polaris_access_token: ${{ secrets.POLARIS_ACCESS_TOKEN }}
          #polaris_assessment_types: "SCA,SAST"


